const express = require("express");
const router = express.Router();
const productRouts = require("./product/productRouts");
const categoryRouts = require("./category/categoryRouts");
const orderRouts = require("./order/orderRouts");
const reviewRouts = require("./review & rating/reviewRouter");
router.use("/categorys", categoryRouts);
router.use("/products", productRouts);
router.use("/order", orderRouts);
router.use("/review", reviewRouts);
module.exports = router;
