const express = require("express");
const dotenv = require("dotenv").config();
const app = express();
const port = process.env.PORT;
const errorHandler = require("./middleware/errorHandler");
const mainRoutes = require("./index");
app.use(express.json());
require("./config/dbConnect");
const syncModels = require("./config/syncFunction");
const relations = require("./config/relations");
const { createOrSearchIndexRedis } = require("./product/productServices");
createOrSearchIndexRedis();
relations();
syncModels();
app.use("/api", mainRoutes);
app.use(errorHandler);
app.listen(port, () => console.log(`Server started on ${port}!`));
